language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - echo $TRAVIS_BUILD_NUMBER

deploy:
  skip_cleanup: true
  provider: script
  script: ruby get_pom_version.rb
