language: java
jdk:
  - oraclejdk7
#  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

script: mvn deploy -DVERSION_SUFFIX=$TRAVIS_BUILD_NUMBER
#  - echo TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
#  - echo TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID
#  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
#  - echo TRAVIS_JOB_ID=$TRAVIS_JOB_ID
#  - echo TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
#  - echo TRAVIS_TAG=$TRAVIS_TAG
#  - echo TRAVIS_JDK_VERSION=$TRAVIS_JDK_VERSION
