language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - echo script

deploy:
  skip_cleanup: true
  provider: script
  script: python build_script.py
